spring:
  application:
    name: itoken-zipkin

server:
  port: 8780

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8760/eureka/

management:
  metrics:
    web:
      server:
        auto-time-requests: false